language: node_js
node_js:
  - 10

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

notifications:
  email: false

install:
  - yarn install

before_script:
  - yarn schema:ci

script:
  - yarn lint && yarn type-check && yarn test && yarn cypress:ci && yarn build

branches:
  only:
    - master
