language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '8'

script: yarn run validate

deploy:
  provider: script
  script:
    - yarn run semantic-release

branches:
  only:
    - master
