language: node_js

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '8'

script: yarn run validate

deploy:
  provider: script
  skip_cleanup: false
  script:
    - brew tap netlify/netlifyctl
    - brew install netlifyctl
    - npm run semantic-release
    - node scripts/deploy-preview.js

branches:
  only:
    - master
