[build]
  command = "yarn build"
  functions = "lambda"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  YARN_VERSION = "1.17.3"
  CYPRESS_INSTALL_BINARY = "0"
