// flow-typed signature: 62500902fcd0408d8aeaaf2f3402e760
// flow-typed version: <<STUB>>/axios-extensions_v^1.1.3/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axios-extensions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'axios-extensions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axios-extensions/esm/cacheAdapterEnhancer' {
  declare module.exports: any;
}

declare module 'axios-extensions/esm/index' {
  declare module.exports: any;
}

declare module 'axios-extensions/esm/throttleAdapterEnhancer' {
  declare module.exports: any;
}

declare module 'axios-extensions/esm/utils/buildUrl' {
  declare module.exports: any;
}

declare module 'axios-extensions/lib/cacheAdapterEnhancer' {
  declare module.exports: any;
}

declare module 'axios-extensions/lib/index' {
  declare module.exports: any;
}

declare module 'axios-extensions/lib/throttleAdapterEnhancer' {
  declare module.exports: any;
}

declare module 'axios-extensions/lib/utils/buildUrl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axios-extensions/esm/cacheAdapterEnhancer.js' {
  declare module.exports: $Exports<'axios-extensions/esm/cacheAdapterEnhancer'>;
}
declare module 'axios-extensions/esm/index.js' {
  declare module.exports: $Exports<'axios-extensions/esm/index'>;
}
declare module 'axios-extensions/esm/throttleAdapterEnhancer.js' {
  declare module.exports: $Exports<'axios-extensions/esm/throttleAdapterEnhancer'>;
}
declare module 'axios-extensions/esm/utils/buildUrl.js' {
  declare module.exports: $Exports<'axios-extensions/esm/utils/buildUrl'>;
}
declare module 'axios-extensions/lib/cacheAdapterEnhancer.js' {
  declare module.exports: $Exports<'axios-extensions/lib/cacheAdapterEnhancer'>;
}
declare module 'axios-extensions/lib/index.js' {
  declare module.exports: $Exports<'axios-extensions/lib/index'>;
}
declare module 'axios-extensions/lib/throttleAdapterEnhancer.js' {
  declare module.exports: $Exports<'axios-extensions/lib/throttleAdapterEnhancer'>;
}
declare module 'axios-extensions/lib/utils/buildUrl.js' {
  declare module.exports: $Exports<'axios-extensions/lib/utils/buildUrl'>;
}
