// flow-typed signature: 29bd97112a68530e2448ca78292e4370
// flow-typed version: <<STUB>>/lodash.uniq_v^4.5.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.uniq'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.uniq' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.uniq/index' {
  declare module.exports: $Exports<'lodash.uniq'>;
}
declare module 'lodash.uniq/index.js' {
  declare module.exports: $Exports<'lodash.uniq'>;
}
