// flow-typed signature: 93b90c237f4d74b0b9cb9b8c4b53f649
// flow-typed version: <<STUB>>/lodash.padstart_v^4.6.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.padstart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.padstart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.padstart/index' {
  declare module.exports: $Exports<'lodash.padstart'>;
}
declare module 'lodash.padstart/index.js' {
  declare module.exports: $Exports<'lodash.padstart'>;
}
