// flow-typed signature: b4d490acf256b28db7f5b662a5286184
// flow-typed version: <<STUB>>/mitt_v^1.1.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mitt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mitt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mitt/dist/mitt.es' {
  declare module.exports: any;
}

declare module 'mitt/dist/mitt' {
  declare module.exports: any;
}

declare module 'mitt/dist/mitt.umd' {
  declare module.exports: any;
}

declare module 'mitt/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mitt/dist/mitt.es.js' {
  declare module.exports: $Exports<'mitt/dist/mitt.es'>;
}
declare module 'mitt/dist/mitt.js' {
  declare module.exports: $Exports<'mitt/dist/mitt'>;
}
declare module 'mitt/dist/mitt.umd.js' {
  declare module.exports: $Exports<'mitt/dist/mitt.umd'>;
}
declare module 'mitt/src/index.js' {
  declare module.exports: $Exports<'mitt/src/index'>;
}
