// flow-typed signature: ff6111a8a75fba1dd34f380c8d6d3bf8
// flow-typed version: <<STUB>>/modular-scale_v1.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'modular-scale'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'modular-scale' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'modular-scale/lib/bin' {
  declare module.exports: any;
}

declare module 'modular-scale/lib/build-scales' {
  declare module.exports: any;
}

declare module 'modular-scale/lib/index' {
  declare module.exports: any;
}

declare module 'modular-scale/lib/log-result' {
  declare module.exports: any;
}

declare module 'modular-scale/lib/modular-scale' {
  declare module.exports: any;
}

declare module 'modular-scale/src/bin' {
  declare module.exports: any;
}

declare module 'modular-scale/src/build-scales' {
  declare module.exports: any;
}

declare module 'modular-scale/src/log-result' {
  declare module.exports: any;
}

declare module 'modular-scale/src/modular-scale' {
  declare module.exports: any;
}

declare module 'modular-scale/test/build-scales.spec' {
  declare module.exports: any;
}

declare module 'modular-scale/test/modular-scale.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'modular-scale/index' {
  declare module.exports: $Exports<'modular-scale'>;
}
declare module 'modular-scale/index.js' {
  declare module.exports: $Exports<'modular-scale'>;
}
declare module 'modular-scale/lib/bin.js' {
  declare module.exports: $Exports<'modular-scale/lib/bin'>;
}
declare module 'modular-scale/lib/build-scales.js' {
  declare module.exports: $Exports<'modular-scale/lib/build-scales'>;
}
declare module 'modular-scale/lib/index.js' {
  declare module.exports: $Exports<'modular-scale/lib/index'>;
}
declare module 'modular-scale/lib/log-result.js' {
  declare module.exports: $Exports<'modular-scale/lib/log-result'>;
}
declare module 'modular-scale/lib/modular-scale.js' {
  declare module.exports: $Exports<'modular-scale/lib/modular-scale'>;
}
declare module 'modular-scale/src/bin.js' {
  declare module.exports: $Exports<'modular-scale/src/bin'>;
}
declare module 'modular-scale/src/build-scales.js' {
  declare module.exports: $Exports<'modular-scale/src/build-scales'>;
}
declare module 'modular-scale/src/log-result.js' {
  declare module.exports: $Exports<'modular-scale/src/log-result'>;
}
declare module 'modular-scale/src/modular-scale.js' {
  declare module.exports: $Exports<'modular-scale/src/modular-scale'>;
}
declare module 'modular-scale/test/build-scales.spec.js' {
  declare module.exports: $Exports<'modular-scale/test/build-scales.spec'>;
}
declare module 'modular-scale/test/modular-scale.spec.js' {
  declare module.exports: $Exports<'modular-scale/test/modular-scale.spec'>;
}
