// flow-typed signature: ebd5ce4b26c4acf0027feb3e37a1b16d
// flow-typed version: <<STUB>>/p-queue_v2.2.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'p-queue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'p-queue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'p-queue/index' {
  declare module.exports: $Exports<'p-queue'>;
}
declare module 'p-queue/index.js' {
  declare module.exports: $Exports<'p-queue'>;
}
