// flow-typed signature: 10866f40cf7d99b3ffbcbc4e307ca799
// flow-typed version: <<STUB>>/raf-schd_v^2.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raf-schd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raf-schd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'raf-schd/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'raf-schd/lib/index.js' {
  declare module.exports: $Exports<'raf-schd/lib/index'>;
}
