// flow-typed signature: 301c8b71ab1510940830c1ad8e8beeff
// flow-typed version: <<STUB>>/react-testing-library_v^1.9.4/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-testing-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-testing-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-testing-library/dist/extend-expect' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/index' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/jest-extensions' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/queries' {
  declare module.exports: any;
}

declare module 'react-testing-library/dist/utils' {
  declare module.exports: any;
}

declare module 'react-testing-library/extend-expect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-testing-library/dist/extend-expect.js' {
  declare module.exports: $Exports<'react-testing-library/dist/extend-expect'>;
}
declare module 'react-testing-library/dist/index.js' {
  declare module.exports: $Exports<'react-testing-library/dist/index'>;
}
declare module 'react-testing-library/dist/jest-extensions.js' {
  declare module.exports: $Exports<'react-testing-library/dist/jest-extensions'>;
}
declare module 'react-testing-library/dist/queries.js' {
  declare module.exports: $Exports<'react-testing-library/dist/queries'>;
}
declare module 'react-testing-library/dist/utils.js' {
  declare module.exports: $Exports<'react-testing-library/dist/utils'>;
}
declare module 'react-testing-library/extend-expect.js' {
  declare module.exports: $Exports<'react-testing-library/extend-expect'>;
}
