const ADD_YEARS = 'ADD_YEARS';
const ADD_ISSUES = 'ADD_ISSUES';
const FETCH_ERROR = 'FETCH_ERROR';
const ADD_PAGES = 'ADD_PAGES';
const INC_ZOOM = 'INC_ZOOM';
const DEC_ZOOM = 'DEC_ZOOM';

export { ADD_YEARS, ADD_ISSUES, FETCH_ERROR, ADD_PAGES, INC_ZOOM, DEC_ZOOM };
