const AUTH_UNAUTHENTICATED = 'AUTH_UNAUTHENTICATED';
const AUTH_IN_PROGRESS = 'AUTH_IN_PROGRESS';
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_ERROR = 'AUTH_ERROR';

export { AUTH_UNAUTHENTICATED, AUTH_IN_PROGRESS, AUTH_SUCCESS, AUTH_ERROR };
