const AWAIT_AUTHENTICATION = 'AWAIT_AUTHENTICATION';
const AUTHENTICATED = 'AUTHENTICATED';
const UNAUTHENTICATED = 'UNAUTHENTICATED';
const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';
const ADD_TOKEN = 'ADD_TOKEN';
const UPDATE_USER = 'UPDATE_USER';

export {
  AWAIT_AUTHENTICATION,
  AUTHENTICATED,
  UNAUTHENTICATED,
  SIGN_IN,
  SIGN_OUT,
  ADD_TOKEN,
  UPDATE_USER,
};
